export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const INCREMENT_CREATE_STEP = 'INCREMENT_CREATE_STEP'
export const DECREMENT_CREATE_STEP = 'DECREMENT_CREATE_STEP'

export const SET_BATTLE = 'SET_BATTLE'
export const SET_BRACKET = 'SET_BRACKET'

export const SET_BATTLE_NAME = 'SET_BATTLE_NAME'
export const SET_BATTLE_DESCRIPTION = 'SET_BATTLE_DESCRIPTION'
export const SET_BATTLE_USERS = 'SET_BATTLE_USERS'
export const SET_BATTLE_STATUS = 'SET_BATTLE_STATUS'
export const SET_BATTLE_AND_STATUS = 'SET_BATTLE_AND_STATUS'
